### ISSUE TITLE
Facing a bug in v 7.1

### ISSUE THREAD

**Issue by NaderJafari** [yasuflatland-lf/damascus#86]
Hi
I executed this command in version 1.1.1 on Windows :
` damascus init -c Nader -p com.liferay.sb.nader -v 7.1`
Then : 
`cd .\nader\`
Then : 
` damascus create`

But i faced this errors Only with -v 7.1 and with -v 7.2 every things is OK : 

`
Started creating service scaffolding. Fetching base.json
Generating *-api, *-service, *-web skeletons for nader
Parsing .\nader\nader-service\service.xml
Running "gradle buildService" to generate the service based on parsed service.xml

> Task :nader-service:buildService FAILED
Please set these arguments. Sample values are:
Exception in thread "main"
        service.api.dir=${basedir}/../portal-kernel/src
        service.auto.import.default.references=true
        service.auto.namespace.tables=false
        service.bean.locator.util=com.liferay.portal.kernel.bean.PortalBeanLocatorUtil
        service.build.number=1
        service.build.number.increment=true
        service.hbm.file=${basedir}/src/META-INF/portal-hbm.xml
        service.impl.dir=${basedir}/src
        service.input.file=${service.file}
        service.model.hints.configs=classpath*:META-INF/portal-model-hints.xml,META-INF/portal-model-hints.xml,classpath*:META-INF/ext-model-hints.xml,classpath*:META-INF/portlet-model-hints.xml
        service.model.hints.file=${basedir}/src/META-INF/portal-model-hints.xml
        service.osgi.module=false
        service.plugin.name=
        service.props.util=com.liferay.portal.util.PropsUtil
org.dom4j.DocumentException: Error on line 2 of document file:///C:/Liferay/Liferay7/liferay-commerce-ws/modules/nader/nader/nader-service/service.xml : The processing instruction target matching "[xX][mM][lL]" is not allowed. Nested exception: The processing instruction target matching "[xX][mM][lL]" is not allowed.        service.read.only.prefixes=fetch,get,has,is,load,reindex,search

        service.resource.actions.configs=META-INF/resource-actions/default.xml,resource-actions/default.xml
        service.resources.dir=${basedir}/src
        service.spring.file=${basedir}/src/META-INF/portal-spring.xml
        service.spring.namespaces=beans
        at org.dom4j.io.SAXReader.read(SAXReader.java:482)
        service.sql.dir=${basedir}/../sql
        at org.dom4j.io.SAXReader.read(SAXReader.java:264)
        service.sql.file=portal-tables.sql
        at com.liferay.portal.tools.ToolsUtil._getContentDocument(ToolsUtil.java:561)
        service.sql.indexes.file=indexes.sql
        at com.liferay.portal.tools.ToolsUtil.getContent(ToolsUtil.java:80)
        service.sql.sequences.file=sequences.sql
        at com.liferay.portal.tools.service.builder.ServiceBuilder.<init>(ServiceBuilder.java:598)
        service.target.entity.name=${service.target.entity.name}
        at com.liferay.portal.tools.service.builder.ServiceBuilder.main(ServiceBuilder.java:229)
        service.test.dir=${basedir}/test/integration
Nested exception:

org.xml.sax.SAXParseException; systemId: file:///C:/Liferay/Liferay7/liferay-commerce-ws/modules/nader/nader/nader-service/service.xml; lineNumber: 2; columnNumber: 6; The processing instruction target matching "[xX][mM][lL]" is not allowed.
You can also customize the generated code by overriding the default templates with these optional system properties:
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)

        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        -Dservice.tpl.bad_alias_names=com/liferay/portal/tools/service/builder/dependencies/bad_alias_names.txt
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        -Dservice.tpl.bad_column_names=com/liferay/portal/tools/service/builder/dependencies/bad_column_names.txt
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        -Dservice.tpl.bad_json_types=com/liferay/portal/tools/service/builder/dependencies/bad_json_types.txt
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
        -Dservice.tpl.bad_table_names=com/liferay/portal/tools/service/builder/dependencies/bad_table_names.txt
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanPIData(Unknown Source)
        -Dservice.tpl.base_mode_impl=com/liferay/portal/tools/service/builder/dependencies/base_mode_impl.ftl
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanPIData(Unknown Source)
        -Dservice.tpl.blob_model=com/liferay/por        at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanPI(Unknown Source)
tal/tools/service/builder/dependencies/blob_model.ftl
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
        -Dservice.tpl.copyright.txt=copyright.txt
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        -Dservice.tpl.ejb_pk=com/liferay/portal/tools/service/builder/dependencies/ejb_pk.ftl
        -Dservice.tpl.exception=com/liferay/portal/tools/service/builder/dependencies/exception.ftl
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
        -Dservice.tpl.extended_model=com/liferay/portal/tools/service/builder/dependencies/extended_model.ftl
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        -Dservice.tpl.extended_model_base_impl=com/liferay/portal/tools/service/builder/dependencies/extended_model_base_impl.ftl
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        -Dservice.tpl.extended_model_impl=com/liferay/portal/tools/service/builder/dependencies/extended_model_impl.ftl
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        -Dservice.tpl.finder=com/liferay/portal/tools/service/builder/dependencies/finder.ftl
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        -Dservice.tpl.finder_base_impl=com/liferay/portal/tools/service/builder/dependencies/finder_base_impl.ftl
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        -Dservice.tpl.finder_util=com/liferay/portal/tools/service/builder/dependencies/finder_util.ftl
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        -Dservice.tpl.hbm_xml=com/liferay/portal/tools/service/builder/dependencies/hbm_xml.ftl
        at org.dom4j.io.SAXReader.read(SAXReader.java:465)
        -Dservice.tpl.json_js=com/liferay/portal/tools/service/builder/dependencies/json_js.ftl
        at org.dom4j.io.SAXReader.read(SAXReader.java:264)
        -Dservice.tpl.json_js_method=com/liferay/portal/tools/service/builder/dependencies/json_js_method.ftl
        at com.liferay.portal.tools.ToolsUtil._getContentDocument(ToolsUtil.java:561)
        -Dservice.tpl.model=com/liferay/portal/tools/service/builder/dependencies/model.ftl
        at com.liferay.portal.tools.ToolsUtil.getContent(ToolsUtil.java:80)
        -Dservice.tpl.model_cache=com/liferay/portal/tools/service/builder/dependencies/model_cache.ftl
        at com.liferay.portal.tools.service.builder.ServiceBuilder.<init>(ServiceBuilder.java:598)
        -Dservice.tpl.model_hints_xml=com/liferay/portal/tools/service/builder/dependencies/model_hints_xml.ftl
        at com.liferay.portal.tools.service.builder.ServiceBuilder.main(ServiceBuilder.java:229)
        -Dservice.tpl.model_impl=com/liferay/portal/tools/service/builder/dependencies/model_impl.ftl
        -Dservice.tpl.model_soap=com/liferay/portal/tools/service/builder/dependencies/model_soap.ftl
        -Dservice.tpl.model_wrapper=com/liferay/portal/tools/service/builder/dependencies/model_wrapper.ftl
        -Dservice.tpl.persistence=com/liferay/portal/tools/service/builder/dependencies/persistence.ftl
        -Dservice.tpl.persistence_impl=com/liferay/portal/tools/service/builder/dependencies/persistence_impl.ftl
        -Dservice.tpl.persistence_util=com/liferay/portal/tools/service/builder/dependencies/persistence_util.ftl
        -Dservice.tpl.props=com/liferay/portal/tools/service/builder/dependencies/props.ftl
        -Dservice.tpl.service=com/liferay/portal/tools/service/builder/dependencies/service.ftl
        -Dservice.tpl.service_base_impl=com/liferay/portal/tools/service/builder/dependencies/service_base_impl.ftl
        -Dservice.tpl.service_clp=com/liferay/portal/tools/service/builder/dependencies/service_clp.ftl
        -Dservice.tpl.service_clp_invoker=com/liferay/portal/tools/service/builder/dependencies/service_clp_invoker.ftl
        -Dservice.tpl.service_clp_message_listener=com/liferay/portal/tools/service/builder/dependencies/service_clp_message_listener.ftl
        -Dservice.tpl.service_clp_serializer=com/liferay/portal/tools/service/builder/dependencies/service_clp_serializer.ftl
        -Dservice.tpl.service_http=com/liferay/portal/tools/service/builder/dependencies/service_http.ftl
        -Dservice.tpl.service_impl=com/liferay/portal/tools/service/builder/dependencies/service_impl.ftl
        -Dservice.tpl.service_props_util=com/liferay/portal/tools/service/builder/dependencies/service_props_util.ftl
        -Dservice.tpl.service_soap=com/liferay/portal/tools/service/builder/dependencies/service_soap.ftl
        -Dservice.tpl.service_util=com/liferay/portal/tools/service/builder/dependencies/service_util.ftl
        -Dservice.tpl.service_wrapper=com/liferay/portal/tools/service/builder/dependencies/service_wrapper.ftl
        -Dservice.tpl.spring_xml=com/liferay/portal/tools/service/builder/dependencies/spring_xml.ftl
        -Dservice.tpl.spring_xml_session=com/liferay/portal/tools/service/builder/dependencies/spring_xml_session.ftl

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nader-service:buildService'.
> Process 'command 'C:\Program Files\Java\jre1.8.0_211\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.10.2-bin.zip'.
        at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:51)
        at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
        at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:41)
        at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Unknown Source)
        at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
        at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:77)
        at com.liferay.damascus.cli.common.CommonUtil.runGradle(CommonUtil.java:152)
        at com.liferay.damascus.cli.CreateCommand.execute(CreateCommand.java:104)
        at com.liferay.damascus.cli.Damascus._runCommand(Damascus.java:144)
        at com.liferay.damascus.cli.Damascus.run(Damascus.java:69)
        at com.liferay.damascus.cli.Damascus.main(Damascus.java:32)
Caused by: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':nader-service:buildService'.
        at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:74)
        at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:49)
        at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:39)
        at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:152)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:124)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
        at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:55)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:50)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:44)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:79)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':nader-service:buildService'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:143)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:40)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:40)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:24)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:46)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:49)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:40)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:33)
        at org.gradle.initialization.DefaultGradleLauncher$ExecuteTasks.run(DefaultGradleLauncher.java:355)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.initialization.DefaultGradleLauncher.runTasks(DefaultGradleLauncher.java:219)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        ... 67 more
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jre1.8.0_211\bin\java.exe'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:395)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:37)
        at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:79)
        at com.liferay.gradle.plugins.service.builder.BuildServiceTask.exec(BuildServiceTask.java:60)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 112 more
`

**Comment by yasuflatland-lf** [comment]
@naderjafari Just fixed that and will release the version soon.

**Comment by mkhhatampoor** [comment]
hi
this bug is in service.xml template file in this address:
C:\Users\nader\.damascus\templates\7.1\service.xml
in this file first line is empty and this line make error.
clear this line and fix the bug.

**Comment by yasuflatland-lf** [comment]
@mkhhatampoor , fixed in version 1.1.2
