### ISSUE TITLE
Error executing damascus create

### ISSUE THREAD

**Issue by empolesecasual** [yasuflatland-lf/damascus#95]
Error executing "damascus create":

```
Running "gradle buildService" to generate the service based on parsed service.xml
Fail to run task <buildService>
java.lang.IllegalArgumentException: Could not determine java version from '11.0.1'.
        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:72)
        at org.gradle.api.JavaVersion.current(JavaVersion.java:82)
        at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.javaDeprecationWarning(UnsupportedJavaRuntimeException.java:36)
        at org.gradle.tooling.internal.consumer.ConnectorServices.checkJavaVersion(ConnectorServices.java:59)
        at org.gradle.tooling.internal.consumer.ConnectorServices.createConnector(ConnectorServices.java:37)
        at org.gradle.tooling.GradleConnector.newConnector(GradleConnector.java:85)
        at com.liferay.damascus.cli.common.CommonUtil.runGradle(CommonUtil.java:145)
        at com.liferay.damascus.cli.CreateCommand.execute(CreateCommand.java:104)
        at com.liferay.damascus.cli.Damascus._runCommand(Damascus.java:144)
        at com.liferay.damascus.cli.Damascus.run(Damascus.java:69)
        at com.liferay.damascus.cli.Damascus.main(Damascus.java:32)
```

**Comment by yasuflatland-lf** [comment]
Hi @empolesecasual , thank you for being interested in Damascus. Let me confirm, are you trying to use Damascus on JDK 11 environment? Unfortunately, Damascus only supports JDK 8 for now.
